import { Type } from "./types";

export const PHILOSOPHERS: Type.Philosopher[] = [
  {
    id: "socrates",
    name: "Socrates",
    period: "Hy Lạp cổ đại",
    years: "470 – 399 TCN",
    school: "Socratic",
    concept: "Phương pháp Socrates",
    quote: "Một cuộc đời không được xem xét thì không đáng sống.",
    description: "Nhân vật nền móng của triết học phương Tây, nổi tiếng với phương pháp đặt câu hỏi để bộc lộ sự thiếu hiểu biết.",
    region: "Phương Tây",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/1200x/9e/2e/cb/9e2ecb72807808b1959cf5e7a224d317.jpg",
    imagePosition: "center 15%"
  },
  {
    id: "plato",
    name: "Plato",
    period: "Hy Lạp cổ đại",
    years: "427 – 347 TCN",
    school: "Chủ nghĩa Platon",
    concept: "Thuyết hình thức",
    quote: "Sự thiếu hiểu biết là cội rễ và thân cây của mọi tội ác.",
    description: "Học trò của Socrates và người sáng lập Viện Hàn lâm. Ông cho rằng thế giới vật chất chỉ là cái bóng của một thực tại cao hơn.",
    region: "Phương Tây",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/736x/37/32/cb/3732cbd6c0dbe79277873059a197c5a4.jpg",
    imagePosition: "center 15%"
  },
  {
    id: "aristotle",
    name: "Aristotle",
    period: "Hy Lạp cổ đại",
    years: "384 – 322 TCN",
    school: "Peripatetic",
    concept: "Đạo đức học Đức hạnh",
    quote: "Chúng ta là những gì chúng ta lặp đi lặp lại. Sự xuất sắc, do đó, không phải là một hành động, mà là một thói quen.",
    description: "Người 'Thầy đầu tiên' đã phân loại kiến thức thành logic, sinh học và đạo đức.",
    region: "Phương Tây",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/736x/ce/9b/66/ce9b66fdda1ded617b03cd23543cf95e.jpg",
    imagePosition: "center 15%"
  },
  {
    id: "heraclitus",
    name: "Heraclitus",
    period: "Hy Lạp cổ đại",
    years: "535 – 475 TCN",
    school: "Tiền Socrates",
    concept: "Sự biến đổi vĩnh cửu",
    quote: "Không ai tắm hai lần trên cùng một dòng sông.",
    description: "Triết gia của sự thay đổi, tin rằng xung đột là cha đẻ của vạn vật và vũ trụ luôn trong trạng thái biến chuyển.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/1200x/35/9b/99/359b99d837a8938a32c7eb2078d9d392.jpg"
  },
  {
    id: "parmenides",
    name: "Parmenides",
    period: "Hy Lạp cổ đại",
    years: "515 – 450 TCN",
    school: "Eleatic",
    concept: "Tính duy nhất của thực tại",
    quote: "Cái gì là, là; cái gì không là, không thể là.",
    description: "Đối lập với Heraclitus, ông cho rằng sự thay đổi là ảo giác và thực tại là một khối duy nhất, bất biến.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/22/bb/84/22bb84523ada8faf5637bb1b602b0bac.jpg"
  },
  {
    id: "democritus",
    name: "Democritus",
    period: "Hy Lạp cổ đại",
    years: "460 – 370 TCN",
    school: "Thuyết nguyên tử",
    concept: "Vũ trụ nguyên tử",
    quote: "Hạnh phúc không nằm ở gia súc hay vàng bạc. Tâm hồn là nơi trú ngụ của hạnh phúc.",
    description: "Triết gia cười, người đã tiên đoán sự tồn tại của nguyên tử và khoảng không vô tận.",
    region: "Phương Tây",
    rarity: "Rất hiếm",
    image: "https://i.pinimg.com/736x/aa/2f/b6/aa2fb685063c00fddf3765cc52a4fb3a.jpg"
  },
  {
    id: "epicurus",
    name: "Epicurus",
    period: "Hy Lạp cổ đại",
    years: "341 – 270 TCN",
    school: "Chủ nghĩa Epicurus",
    concept: "Ataraxia (Sự thanh thản)",
    quote: "Cái chết không là gì đối với chúng ta.",
    description: "Ông dạy rằng mục đích của cuộc sống là tìm kiếm niềm vui bền vững thông qua sự vắng bóng của nỗi đau và nỗi sợ.",
    region: "Phương Tây",
    rarity: "Rất hiếm",
    image: "https://i.pinimg.com/736x/e5/92/28/e592287eddfcf24e179160d0b55751bd.jpg"
  },
  {
    id: "zeno-of-citium",
    name: "Zeno of Citium",
    period: "Hy Lạp cổ đại",
    years: "334 – 262 TCN",
    school: "Chủ nghĩa khắc kỷ",
    concept: "Sống thuận theo tự nhiên",
    quote: "Hạnh phúc là dòng chảy êm đềm của cuộc sống.",
    description: "Người sáng lập chủ nghĩa Khắc kỷ, dạy rằng đức hạnh là điều thiện duy nhất và lý trí là người dẫn đường.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/94/e7/12/94e71296db21c61baa7449a872041c9a.jpg"
  },
  {
    id: "diogenes",
    name: "Diogenes",
    period: "Hy Lạp cổ đại",
    years: "412 – 323 TCN",
    school: "Chủ nghĩa khuyển nho",
    concept: "Sự tự chủ tuyệt đối",
    quote: "Tôi đang tìm một con người thực sự.",
    description: "Triết gia sống trong một cái chum, nổi tiếng với việc thách thức mọi quy ước xã hội để tìm kiếm sự thật.",
    region: "Phương Tây",
    rarity: "Rất hiếm",
    image: "https://i.pinimg.com/736x/da/5a/05/da5a05e7ec03fd16676584146dd11922.jpg"
  },
  {
    id: "pythagoras",
    name: "Pythagoras",
    period: "Hy Lạp cổ đại",
    years: "570 – 495 TCN",
    school: "Chủ nghĩa Pythagoras",
    concept: "Vũ trụ là con số",
    quote: "Con số cai trị vũ trụ.",
    description: "Nhà toán học và triết gia thần bí, người tin rằng âm nhạc, toán học và tâm hồn có mối liên hệ mật thiết.",
    region: "Phương Tây",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/736x/b8/76/ae/b876ae00ea5b9912c052df7ccd6e1357.jpg"
  },
  {
    id: "seneca",
    name: "Seneca the Younger",
    period: "La Mã",
    years: "4 TCN – 65 CN",
    school: "Chủ nghĩa khắc kỷ",
    concept: "Sự ngắn ngủi của cuộc đời",
    quote: "Chúng ta đau khổ trong trí tưởng tượng nhiều hơn là trong thực tế.",
    description: "Cố vấn của bạo chúa Nero, người đã viết những bức thư sâu sắc về cách đối mặt với nghịch cảnh.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/1200x/90/4c/62/904c62ccb5347497a71db523bc6352ca.jpg"
  },
  {
    id: "marcus-aurelius",
    name: "Marcus Aurelius",
    period: "La Mã",
    years: "121 – 180 CN",
    school: "Chủ nghĩa khắc kỷ",
    concept: "Thành trì nội tâm",
    quote: "Hạnh phúc của cuộc đời bạn phụ thuộc vào chất lượng những suy nghĩ của bạn.",
    description: "Hoàng đế La Mã và triết gia Khắc kỷ, người đã viết 'Suy tưởng' như một lời hướng dẫn cá nhân.",
    region: "Phương Tây",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/736x/66/19/49/661949bf3790454b8f259c2d2bb6f9ff.jpg"
  },
  {
    id: "epictetus",
    name: "Epictetus",
    period: "La Mã",
    years: "50 – 135 CN",
    school: "Chủ nghĩa khắc kỷ",
    concept: "Sự phân biệt kiểm soát",
    quote: "Không phải sự việc làm ta phiền muộn, mà là cách ta nhìn nhận chúng.",
    description: "Một nô lệ trở thành triết gia, dạy rằng tự do thực sự nằm ở việc kiểm soát tâm trí của chính mình.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/e6/00/b7/e600b795c3df2593822eaa648fadaa6c.jpg"
  },
  {
    id: "augustine",
    name: "Augustine of Hippo",
    period: "Trung cổ",
    years: "354 – 430 CN",
    school: "Triết học Kitô giáo",
    concept: "Thành phố của Chúa",
    quote: "Yêu đi, rồi làm gì thì làm.",
    description: "Một trong những người cha của Giáo hội, người đã kết hợp triết học Hy Lạp với thần học Kitô giáo.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/94/fe/c1/94fec19405432080a1795e5b2ce5f21b.jpg"
  },
  {
    id: "aquinas",
    name: "Thomas Aquinas",
    period: "Trung cổ",
    years: "1225 – 1274",
    school: "Kinh viện",
    concept: "Năm cách chứng minh Chúa",
    quote: "Đức tin tìm kiếm sự hiểu biết.",
    description: "Triết gia vĩ đại nhất của thời Trung cổ, người đã hòa giải đức tin và lý trí thông qua tư tưởng Aristotle.",
    region: "Phương Tây",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/1200x/ac/4a/33/ac4a33afd80ace5b49deefdd21576954.jpg"
  },
  {
    id: "avicenna",
    name: "Avicenna",
    period: "Trung cổ",
    years: "980 – 1037",
    school: "Triết học Hồi giáo",
    concept: "Thí nghiệm người bay",
    quote: "Thế giới là một cuốn sách, và những người không đi du lịch chỉ đọc được một trang.",
    description: "Đa tài người Ba Tư, người đã bảo tồn triết học Hy Lạp và đặt nền móng cho y học hiện đại.",
    region: "Phương Đông",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/736x/5f/24/28/5f24289bc82317281a824ca33f2d20b4.jpg"
  },
  {
    id: "averroes",
    name: "Averroes",
    period: "Trung cổ",
    years: "1126 – 1198",
    school: "Triết học Hồi giáo",
    concept: "Sự hòa hợp giữa tôn giáo và triết học",
    quote: "Sự thiếu hiểu biết dẫn đến nỗi sợ hãi, nỗi sợ hãi dẫn đến lòng thù hận.",
    description: "Được biết đến là 'Người bình luận' vĩ đại nhất về Aristotle, ảnh hưởng sâu sắc đến châu Âu thời Phục hưng.",
    region: "Phương Đông",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/11/7f/5e/117f5e2e02088b575f89560477725a8a.jpg"
  },
  {
    id: "descartes",
    name: "René Descartes",
    period: "Khai sáng",
    years: "1596 – 1650",
    school: "Chủ nghĩa duy lý",
    concept: "Cogito Ergo Sum",
    quote: "Tôi tư duy, nên tôi tồn tại.",
    description: "Cha đẻ của triết học hiện đại, người đã sử dụng sự hoài nghi phương pháp luận để tìm kiếm sự chắc chắn.",
    region: "Phương Tây",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/736x/8b/ed/a1/8beda1ab667bfd7e11cedd8b246c8215.jpg"
  },
  {
    id: "spinoza",
    name: "Baruch Spinoza",
    period: "Khai sáng",
    years: "1632 – 1677",
    school: "Chủ nghĩa duy lý",
    concept: "Chủ nghĩa nhất nguyên",
    quote: "Tất cả những điều cao quý đều khó khăn cũng như hiếm có.",
    description: "Ông cho rằng Chúa và Thiên nhiên là một, và tự do nằm ở việc hiểu biết sự tất yếu của vũ trụ.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/45/83/06/4583065633a4125df2ee303d0ced5236.jpg"
  },
  {
    id: "locke",
    name: "John Locke",
    period: "Khai sáng",
    years: "1632 – 1704",
    school: "Chủ nghĩa kinh nghiệm",
    concept: "Tabula Rasa (Bảng sạch)",
    quote: "Kiến thức của con người không thể vượt qua kinh nghiệm của họ.",
    description: "Cha đẻ của chủ nghĩa tự do, tin rằng mọi kiến thức đều đến từ giác quan và con người có quyền tự nhiên.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/1200x/72/8a/40/728a40acc3039a143ae268cd9e2d7e21.jpg"
  },
  {
    id: "hume",
    name: "David Hume",
    period: "Khai sáng",
    years: "1711 – 1776",
    school: "Chủ nghĩa kinh nghiệm",
    concept: "Vấn đề quy nạp",
    quote: "Lý trí là nô lệ của những đam mê.",
    description: "Nhà hoài nghi triệt để, người đã thách thức các khái niệm về nguyên nhân và bản sắc cá nhân.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/1200x/3e/12/e0/3e12e00493a90514104a136ae8ac5215.jpg"
  },
  {
    id: "kant",
    name: "Immanuel Kant",
    period: "Khai sáng",
    years: "1724 – 1804",
    school: "Chủ nghĩa Kant",
    concept: "Mệnh lệnh tuyệt đối",
    quote: "Hãy dám biết! (Sapere Aude)",
    description: "Ông đã tổng hợp chủ nghĩa duy lý và kinh nghiệm, khẳng định tâm trí định hình cách chúng ta trải nghiệm thế giới.",
    region: "Phương Tây",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/736x/7c/a1/16/7ca116d0b73e4fb776d5027f44ade659.jpg"
  },
  {
    id: "rousseau",
    name: "Jean-Jacques Rousseau",
    period: "Khai sáng",
    years: "1712 – 1778",
    school: "Chủ nghĩa lãng mạn",
    concept: "Ý chí phổ quát",
    quote: "Con người sinh ra tự do, nhưng ở khắp nơi họ đều bị xiềng xích.",
    description: "Ông tin vào sự tốt đẹp tự nhiên của con người và tầm quan trọng của hợp đồng xã hội.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/47/28/23/4728238655fb78ef97fa00b47c6d0666.jpg"
  },
  {
    id: "voltaire",
    name: "Voltaire",
    period: "Khai sáng",
    years: "1694 – 1778",
    school: "Chủ nghĩa khai sáng",
    concept: "Tự do ngôn luận",
    quote: "Tôi không đồng ý với những gì bạn nói, nhưng tôi sẽ bảo vệ đến cùng quyền được nói của bạn.",
    description: "Nhà văn và triết gia sắc sảo, người đã chiến đấu chống lại sự giáo điều và bất công xã hội.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/1200x/0f/d9/aa/0fd9aa7640966c16e416dd9b54c0ddd1.jpg"
  },
  {
    id: "hegel",
    name: "G.W.F. Hegel",
    period: "Hiện đại",
    years: "1770 – 1831",
    school: "Chủ nghĩa duy tâm Đức",
    concept: "Phép biện chứng",
    quote: "Cái gì hợp lý thì thực tế, cái gì thực tế thì hợp lý.",
    description: "Ông nhìn nhận lịch sử như một quá trình tiến hóa của Tinh thần thông qua mâu thuẫn và tổng hợp.",
    region: "Phương Tây",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/736x/32/6a/db/326adbdf9e1fea326a5f6fea20903c93.jpg"
  },
  {
    id: "schopenhauer",
    name: "Arthur Schopenhauer",
    period: "Hiện đại",
    years: "1788 – 1860",
    school: "Chủ nghĩa bi quan",
    concept: "Thế giới như là ý chí",
    quote: "Cuộc đời dao động như một con lắc giữa nỗi đau và sự nhàm chán.",
    description: "Ông cho rằng một ý chí mù quáng, không ngừng nghỉ là bản chất của thực tại và nguồn gốc của khổ đau.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/e8/88/c1/e888c1de59399e98cae8e673ffe8092f.jpg"
  },
  {
    id: "nietzsche",
    name: "Friedrich Nietzsche",
    period: "Hiện đại",
    years: "1844 – 1900",
    school: "Chủ nghĩa hiện sinh",
    concept: "Übermensch (Siêu nhân)",
    quote: "Cái gì không giết chết được ta sẽ làm ta mạnh mẽ hơn.",
    description: "Ông kêu gọi sự đánh giá lại mọi giá trị và sự khẳng định cuộc sống trước sự hư vô.",
    region: "Phương Tây",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/736x/c5/2c/19/c52c196754ba5662fe90509e85488715.jpg"
  },
  {
    id: "marx",
    name: "Karl Marx",
    period: "Hiện đại",
    years: "1818 – 1883",
    school: "Chủ nghĩa duy vật lịch sử",
    concept: "Đấu tranh giai cấp",
    quote: "Các triết gia mới chỉ giải thích thế giới; vấn đề là phải thay đổi nó.",
    description: "Nhà kinh tế và triết gia, người đã phân tích sự tha hóa của con người trong chủ nghĩa tư bản.",
    region: "Phương Tây",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/736x/b1/7a/07/b17a0735192705049880797c5d62797d.jpg"
  },
  {
    id: "mill",
    name: "John Stuart Mill",
    period: "Hiện đại",
    years: "1806 – 1873",
    school: "Chủ nghĩa tiện lợi",
    concept: "Nguyên tắc tự do",
    quote: "Thà làm một con người không thỏa mãn còn hơn làm một con lợn thỏa mãn.",
    description: "Người bảo vệ mạnh mẽ cho tự do cá nhân và quyền của phụ nữ.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/d8/fa/d7/d8fad70df06db889c74f25dba7f4af2a.jpg"
  },
  {
    id: "comte",
    name: "Auguste Comte",
    period: "Hiện đại",
    years: "1798 – 1857",
    school: "Chủ nghĩa thực chứng",
    concept: "Quy luật ba giai đoạn",
    quote: "Tình yêu là nguyên tắc, trật tự là nền tảng, tiến bộ là mục tiêu.",
    description: "Cha đẻ của xã hội học, người tin rằng khoa học nên được sử dụng để cải tổ xã hội.",
    region: "Phương Tây",
    rarity: "Rất hiếm",
    image: "https://i.pinimg.com/1200x/71/c7/26/71c726f7cec0f5dee1e884328f397ce2.jpg"
  },
  {
    id: "wittgenstein",
    name: "Ludwig Wittgenstein",
    period: "Thế kỷ 20",
    years: "1889 – 1951",
    school: "Triết học ngôn ngữ",
    concept: "Trò chơi ngôn ngữ",
    quote: "Giới hạn của ngôn ngữ là giới hạn của thế giới tôi.",
    description: "Ông đã cách mạng hóa triết học bằng cách tập trung vào cách ngôn ngữ định hình tư duy.",
    region: "Phương Tây",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/736x/81/d4/db/81d4db945a2c1c15bececd762dc9360c.jpg"
  },
  {
    id: "heidegger",
    name: "Martin Heidegger",
    period: "Thế kỷ 20",
    years: "1889 – 1976",
    school: "Hiện tượng học",
    concept: "Dasein (Hiện hữu ở đó)",
    quote: "Tại sao lại có cái gì đó thay vì không có gì?",
    description: "Ông tìm kiếm ý nghĩa của Sự hữu và phân tích sự tồn tại của con người trong thế giới.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/d2/b7/21/d2b721f2f8bbe024edd076b1903f11f2.jpg"
  },
  {
    id: "sartre",
    name: "Jean-Paul Sartre",
    period: "Thế kỷ 20",
    years: "1905 – 1980",
    school: "Chủ nghĩa hiện sinh",
    concept: "Hiện hữu có trước bản chất",
    quote: "Con người bị kết án phải tự do.",
    description: "Nhân vật chủ chốt của chủ nghĩa hiện sinh, nhấn mạnh vào trách nhiệm cá nhân tuyệt đối.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/5e/47/9f/5e479fb54e444dec4b437114971665e2.jpg"
  },
  {
    id: "beauvoir",
    name: "Simone de Beauvoir",
    period: "Thế kỷ 20",
    years: "1908 – 1986",
    school: "Chủ nghĩa nữ quyền",
    concept: "Giới tính thứ hai",
    quote: "Người ta không sinh ra là phụ nữ, mà trở thành phụ nữ.",
    description: "Bà đã đặt nền móng cho nữ quyền hiện đại thông qua phân tích hiện sinh về vị thế của phụ nữ.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/42/77/29/4277290b95fa9b2f3454a9b4e5846d87.jpg"
  },
  {
    id: "camus",
    name: "Albert Camus",
    period: "Thế kỷ 20",
    years: "1913 – 1960",
    school: "Chủ nghĩa phi lý",
    concept: "Huyền thoại Sisyphus",
    quote: "Giữa mùa đông, tôi nhận ra trong tôi có một mùa hè bất tận.",
    description: "Ông khám phá sự phi lý của cuộc đời và cách con người tìm thấy ý nghĩa thông qua sự nổi loạn.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/1200x/14/3b/c5/143bc5e8aa2f4b8938b8a3d9f256d1d3.jpg"
  },
  {
    id: "foucault",
    name: "Michel Foucault",
    period: "Thế kỷ 20",
    years: "1926 – 1984",
    school: "Cấu trúc luận",
    concept: "Quyền lực và tri thức",
    quote: "Ở đâu có quyền lực, ở đó có sự kháng cự.",
    description: "Ông phân tích cách các tổ chức xã hội sử dụng tri thức để kiểm soát con người.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/1200x/cf/6f/f9/cf6ff9ab3c8914ace6277124f0b6aba7.jpg"
  },
  {
    id: "derrida",
    name: "Jacques Derrida",
    period: "Thế kỷ 20",
    years: "1930 – 2004",
    school: "Giải cấu trúc",
    concept: "Sự khác biệt (Différance)",
    quote: "Không có gì nằm ngoài văn bản.",
    description: "Ông thách thức các hệ thống tư tưởng truyền thống bằng cách bộc lộ những mâu thuẫn nội tại của chúng.",
    region: "Phương Tây",
    rarity: "Rất hiếm",
    image: "https://i.pinimg.com/1200x/e2/91/34/e291346201efdf84e7fa956d22d61ac8.jpg"
  },
  {
    id: "confucius",
    name: "Khổng Tử",
    period: "Phương Đông",
    years: "551 – 479 TCN",
    school: "Nho giáo",
    concept: "Nhân, nghĩa, lễ, trí, tín",
    quote: "Kỷ sở bất dục, vật thi ư nhân (Cái gì mình không muốn thì đừng làm cho người khác).",
    description: "Nhà giáo dục vĩ đại, người đã định hình văn hóa và đạo đức Đông Á trong hàng thiên niên kỷ.",
    region: "Phương Đông",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/736x/bf/b7/c0/bfb7c059bf86c7b8751cbcf894663372.jpg"
  },
  {
    id: "laozi",
    name: "Lão Tử",
    period: "Phương Đông",
    years: "Thế kỷ 6 TCN",
    school: "Đạo giáo",
    concept: "Đạo và đức",
    quote: "Hành trình vạn dặm bắt đầu từ một bước chân.",
    description: "Ông dạy về sự hài hòa với tự nhiên và sức mạnh của sự mềm mỏng.",
    region: "Phương Đông",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/736x/5c/50/9f/5c509f4257c22684414e0b4d782d21db.jpg"
  },
  {
    id: "zhuangzi",
    name: "Trang Tử",
    period: "Phương Đông",
    years: "369 – 286 TCN",
    school: "Đạo giáo",
    concept: "Giấc mộng hồ điệp",
    quote: "Hạnh phúc là sự vắng mặt của nỗ lực tìm kiếm hạnh phúc.",
    description: "Triết gia của sự tự do tuyệt đối và trí tưởng tượng bay bổng.",
    region: "Phương Đông",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/1200x/6b/ca/4d/6bca4da56c60bb06339028228ae76cec.jpg"
  },
  {
    id: "sun-tzu",
    name: "Tôn Tử",
    period: "Phương Đông",
    years: "544 – 496 TCN",
    school: "Binh pháp",
    concept: "Nghệ thuật chiến tranh",
    quote: "Biết người biết ta, trăm trận không nguy.",
    description: "Nhà chiến lược lỗi lạc, người đã biến chiến tranh thành một môn nghệ thuật của trí tuệ.",
    region: "Phương Đông",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/0d/78/85/0d7885944a09bfe0ce9c1725d1125d9e.jpg"
  },
  {
    id: "buddha",
    name: "Gautama Buddha",
    period: "Ấn Độ",
    years: "563 – 483 TCN",
    school: "Phật giáo",
    concept: "Tứ diệu đế",
    quote: "Tâm trí là tất cả. Bạn nghĩ gì, bạn trở thành cái đó.",
    description: "Người thức tỉnh, dạy con đường thoát khỏi khổ đau thông qua chánh niệm và từ bi.",
    region: "Phương Đông",
    rarity: "Huyền thoại",
    image: "https://i.pinimg.com/736x/e1/1f/e0/e11fe0755bf8230502fe5738a01a3ffa.jpg"
  },
  {
    id: "nagarjuna",
    name: "Nagarjuna",
    period: "Ấn Độ",
    years: "150 – 250 CN",
    school: "Trung quán tông",
    concept: "Tính không (Sunyata)",
    quote: "Mọi thứ đều tồn tại tương đối, không có gì có bản chất tự thân.",
    description: "Một trong những triết gia Phật giáo quan trọng nhất, người đã phát triển logic về tính Không.",
    region: "Phương Đông",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/e8/ee/83/e8ee83a0b19b8206dbe4ea6b5c376b10.jpg"
  },
  {
    id: "arendt",
    name: "Hannah Arendt",
    period: "Đương đại",
    years: "1906 – 1975",
    school: "Triết học chính trị",
    concept: "Sự tầm thường của cái ác",
    quote: "Trong những hoàn cảnh bạo lực, im lặng là đồng lõa.",
    description: "Bà đã phân tích bản chất của chủ nghĩa độc tài và tầm quan trọng của hành động chính trị.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/ee/9c/4a/ee9c4a6a3a1d20500333dd7097e85e04.jpg"
  },
  {
    id: "popper",
    name: "Karl Popper",
    period: "Đương đại",
    years: "1902 – 1994",
    school: "Triết học khoa học",
    concept: "Khả năng bác bỏ (Falsifiability)",
    quote: "Kiến thức thực sự là biết rằng chúng ta không biết gì.",
    description: "Ông bảo vệ xã hội mở và định nghĩa khoa học thông qua khả năng bị chứng minh là sai.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/9f/b5/39/9fb5393e407accd5c954b17b09e8164a.jpg"
  },
  {
    id: "kuhn",
    name: "Thomas Kuhn",
    period: "Đương đại",
    years: "1922 – 1996",
    school: "Triết học khoa học",
    concept: "Chuyển đổi hệ hình (Paradigm Shift)",
    quote: "Sự thật không chiến thắng bằng cách thuyết phục đối thủ, mà vì đối thủ cuối cùng sẽ chết đi.",
    description: "Ông đã thay đổi cách chúng ta hiểu về sự tiến bộ của khoa học thông qua các cuộc cách mạng.",
    region: "Phương Tây",
    rarity: "Rất hiếm",
    image: "https://i.pinimg.com/736x/75/76/87/75768757eba9438229842d5443a4c822.jpg"
  },
  {
    id: "rawls",
    name: "John Rawls",
    period: "Đương đại",
    years: "1921 – 2002",
    school: "Chủ nghĩa tự do",
    concept: "Bức màn vô tri",
    quote: "Công bằng là đức hạnh đầu tiên của các định chế xã hội.",
    description: "Ông đã hồi sinh triết học chính trị với lý thuyết về công bằng như là sự bình đẳng.",
    region: "Phương Tây",
    rarity: "Sử thi",
    image: "https://i.pinimg.com/736x/76/92/56/769256974daf3dd08a5e0711ee400394.jpg"
  },
  {
    id: "singer",
    name: "Peter Singer",
    period: "Đương đại",
    years: "1946 – Nay",
    school: "Chủ nghĩa tiện lợi",
    concept: "Giải phóng động vật",
    quote: "Nếu chúng ta có thể ngăn chặn điều gì đó xấu xa mà không phải hy sinh điều gì có tầm quan trọng tương đương, chúng ta nên làm điều đó.",
    description: "Triết gia đạo đức nổi tiếng với các công trình về quyền động vật và lòng nhân ái hiệu quả.",
    region: "Phương Tây",
    rarity: "Rất hiếm",
    image: "https://i.pinimg.com/736x/1e/79/10/1e79107344ca29dcd6cc1315efb06405.jpg"
  },
  {
    id: "zizek",
    name: "Slavoj Žižek",
    period: "Đương đại",
    years: "1949 – Nay",
    school: "Phân tâm học Lacan",
    concept: "Hệ tư tưởng như là ảo tưởng",
    quote: "Tôi không muốn một thế giới không có những mâu thuẫn.",
    description: "Triết gia văn hóa nổi tiếng với cách tiếp cận khiêu khích và hài hước về chính trị và điện ảnh.",
    region: "Phương Tây",
    rarity: "Rất hiếm",
    image: "https://i.pinimg.com/736x/c9/7f/51/c97f51f3afbb625a67c436456d5dd54e.jpg"
  },
  {
    id: "han",
    name: "Byung-Chul Han",
    period: "Đương đại",
    years: "1959 – Nay",
    school: "Triết học xã hội",
    concept: "Xã hội mệt mỏi",
    quote: "Bạo lực của sự tích cực còn tồi tệ hơn bạo lực của sự tiêu cực.",
    description: "Triết gia người Đức gốc Hàn, nổi tiếng với các phân tích về sự kiệt sức trong xã hội kỹ thuật số.",
    region: "Phương Tây",
    rarity: "Rất hiếm",
    image: "https://i.pinimg.com/1200x/71/df/c6/71dfc683c1d56d4f356423b81f9a2c3e.jpg"
  }
];
